update text, english only (for now)
Iapetus-11/Villager-Bot pull request #102
Opened 2021-03-18 06:28 UTC by quaackk

mmm punctuation, is this too many :/

2021-03-18 12:19 UTC, Iapetus-11 commented on data/text.json
> +        "clap":"`{0}clap <text>` *:clap: puts :clap: the :clap: clap :clap: emoji :clap: between :clap: text :clap:*",
This was intentional but ok

2021-03-18 12:21 UTC, Iapetus-11 requested changes

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **zombie** ran, lashing at your arms.",
Perhaps use exclamation points here?

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **skeleboi** yeets an arrow at your face.",
! here too

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **spider** jumps on top of you and sinks its fangs into your arm.",
and here

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **spider** rips your face off, your last sight being 8 murderous red eyes staring back."
and here

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **cave spider**'s fangs digs deep onto your skin.",
and here

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "You died a slow, painful death from poison damage.",
and here

2021-03-18 12:21 UTC, Iapetus-11 commented on data/text.json
> +            "The **baby slime** jumps on you.",
and here

2021-03-18 16:00 UTC, quaackk commented
that should be all of them

2021-03-19 12:05 UTC, Iapetus-11 requested changes

2021-03-19 12:05 UTC, Iapetus-11 commented on data/text.json
> +            "BOOM! HEADSHOT! - **skeleton 2021**"
This was correct the way it was.

2021-03-19 18:31 UTC, quaackk commented
i swear, ok is this everything now

2021-03-19 18:39 UTC, Iapetus-11 approved these changes

2021-03-19 18:39 UTC, merged