Slime
Iapetus-11/Villager-Bot pull request #159
Opened 2021-05-22 15:46 UTC by kaosj314

This will increase the amount (not chances _yet_) for slime drops when having looting.

2021-05-22 21:35 UTC, Iapetus-11 requested changes

2021-05-22 21:35 UTC, Iapetus-11 commented on src/cogs/other/mobs.py
> +                    balls_won = round(balls_won)
add a newline after indentation changes

2021-05-23 04:48 UTC, kaosj314 commented on src/cogs/other/mobs.py
> +                    balls_won = round(balls_won)
oh! fixing now

2021-05-23 15:59 UTC, Iapetus-11 approved these changes

2021-05-23 15:59 UTC, merged