Add inventory_transfer command
Iapetus-11/Villager-Bot pull request #256
Opened 2023-03-15 15:52 UTC by Infernum1

2023-03-15 22:06 UTC, Iapetus-11 requested changes
1. This doesn't remove items from the `from_user`
2. It would be nice to have a "summary" of items moved just in case, I think a separate command which is called `!!debuginv <user>` would be nice and it lists out their items like:
```
({user_id}, {item_name}, {sell_price}, {amount}, {sticky}, {sellable}),
...
```
for easy db inserts

2023-03-15 22:06 UTC, Iapetus-11 requested changes
1. This doesn't remove items from the `from_user`
2. It would be nice to have a "summary" of items moved just in case, I think a separate command which is called `!!debuginv <user>` would be nice and it lists out their items like:
```
({user_id}, {item_name}, {sell_price}, {amount}, {sticky}, {sellable}),
...
```
for easy db inserts

2023-03-15 22:06 UTC, Iapetus-11 commented on bot/cogs/commands/owner.py
> +        await ctx.send(f"{self.d.emojis.yes} Transferred **{item_count}** items from {from_user.mention} to {to_user.mention}.")
Can this be a reply instead

2023-03-16 02:58 UTC, Infernum1 commented
> 1. This doesn't remove items from the `from_user`
> 2. It would be nice to have a "summary" of items moved just in case, I think a separate command which is called `!!debuginv <user>` would be nice and it lists out their items like:
> ```
> ({user_id}, {item_name}, {sell_price}, {amount}, {sticky}, {sellable}),
> ...
> ```
> for easy db inserts

Oh sure I totally forgot about that, also the two things you mentioned (a summary and another debug command) are seperate right? Just a lil confused about that

2023-03-16 02:59 UTC, Infernum1 commented on bot/cogs/commands/owner.py
> +        await ctx.send(f"{self.d.emojis.yes} Transferred **{item_count}** items from {from_user.mention} to {to_user.mention}.")
Sure sure

2023-03-17 12:58 UTC, Iapetus-11 requested changes

2023-03-17 12:58 UTC, Iapetus-11 commented on bot/cogs/commands/owner.py
> +    async def transfer_inventory(self, ctx: Ctx, from_user: discord.User, to_user: discord.User):
Can you make this take `int | discord.User` so that this can handle users which don't share any servers with the bot?

2023-03-17 17:16 UTC, Iapetus-11 approved these changes

2023-03-17 17:16 UTC, Iapetus-11 commented
Ty

2023-03-17 17:16 UTC, merged