Add 4th of July Event items
Iapetus-11/Villager-Bot pull request #293
Opened 2024-06-28 13:39 UTC by ZethalMC

Some items are missing textures. They'll be added as soon as I have them finished.

2024-06-28 13:48 UTC, ZethalMC commented
I am just bad at using separators 😄

2024-06-28 14:05 UTC, ZethalMC commented
Finally! Have fun!

2024-06-28 14:30 UTC, orange-bazookas commented
the items have way too high sell values for their rarity, and imo you could have just used last year's 4th of july items instead of making new ones

2024-06-28 14:32 UTC, orange-bazookas commented
it also seems not all items are mine&fish, is this a bug?

2024-06-29 13:41 UTC, ZethalMC commented
> the items have way too high sell values for their rarity, and imo you could have just used last year's 4th of july items instead of making new ones

This is fixed right away.

2024-06-29 13:42 UTC, ZethalMC commented
> it also seems not all items are mine&fish, is this a bug?

This is not a bug, just to make the items a bit more random. Some normal items can't be fished or mined too, as they're specific to one method.

2024-06-29 14:06 UTC, Iapetus-11 commented on common/data/data.json
> +    "a_literal_bonfire": "<:air:828359049602662431>",
For items with no emoji just don't add them here ig

2024-06-29 14:06 UTC, Iapetus-11 requested changes
I think a few should be removed:
- Eating Competition Prize
- A Literal Bonfire
- 4th Of July Decorations
- Lady Liberty Tabula Ansata
- Lady Liberty Torch
- Declaration Of Independence
- Freedom Firework Bundle

But I do like the rest, we could also maybe add:
- Komodo 30000 SuperNova Aerial Firework (with a bomb emoji)

2024-06-29 22:41 UTC, closed without merging

2024-06-29 22:41 UTC, Iapetus-11 commented
@ZethalMC Since you opened this from your `main` branch I can't push changes to it...
<img width="678" alt="image" src="https://github.com/Iapetus-11/Villager-Bot/assets/38477514/3be7dda7-25ce-4edf-9faa-16a3cdc5475d">

I'm going to close this PR and make a new one off your branch.